Add Outage
freifunkMUC/freifunkmuc.github.io pull request #332
Opened 2022-05-23 07:59 UTC by T0biii

addes the Cert Issoue Outage.
took the time from here: https://chat.ffmuc.net/freifunk/pl/tbyoj6q8qtgwxc8k9qz6fkrqao

I take Text suggestions gladly :)

2022-05-23 08:10 UTC, T0biii commented on _includes/network-status.md
>  <br><b>01.10.2020 10:20 - 13:46</b> Ausfall des DoT Servers (dot.ffmuc.net)
I would not delete historical data

2022-05-23 08:24 UTC, GoliathLabs commented on _includes/network-status.md
>  <br><b>01.10.2020 10:20 - 13:46</b> Ausfall des DoT Servers (dot.ffmuc.net)
Why? Some incidents are over two years old. We do not track every small incident and listing many (especially) old ones makes the website visitor think that we do not have a reliable infrastructure.

2022-05-23 08:40 UTC, krombel requested changes

2022-05-23 08:40 UTC, krombel commented on _includes/network-status.md
> +<br><b>22.05.2022 23:43 - 23.05.2022 09:25</b> Ausfall einzelener FFMUC Dienste (z.B. DoT, Chat, Ticket-System, CryptPad)
s/einzelener/einzelner/

2022-05-23 08:51 UTC, T0biii commented on _includes/network-status.md
>  <br><b>01.10.2020 10:20 - 13:46</b> Ausfall des DoT Servers (dot.ffmuc.net)
mh maybe we should than setup the status.ffmuc.net Page
Where we can easyl show if we go a Problem?

2022-06-03 14:00 UTC, GoliathLabs approved these changes

2022-06-04 19:30 UTC, GoliathLabs commented
@T0biii why did you close this PR?

2022-06-04 19:31 UTC, T0biii commented
oh wasn't on purpose

2022-06-05 06:05 UTC, awlx approved these changes

2022-06-05 12:56 UTC, T0biii commented
cant merge this pr

2022-06-05 16:09 UTC, merged